name: vroger11/pre-commit-action
description: run pre-commit as a github action
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  skip:
    description: list of hook ids to skip
    required: false
    default: ''
runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - uses: actions/cache@v3
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: SKIP=${{ inputs.skip }} pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
